//go:build windows

package hotkey

import nativehotkey "golang.design/x/hotkey"

var modifiers = map[string]nativehotkey.Modifier{
	"alt":     nativehotkey.ModAlt,
	"ctrl":    nativehotkey.ModCtrl,
	"control": nativehotkey.ModCtrl,
	"shift":   nativehotkey.ModShift,
	"super":   nativehotkey.ModWin,
	"win":     nativehotkey.ModWin,
}

var keys = map[string]nativehotkey.Key{
	"space":  nativehotkey.KeySpace,
	"enter":  nativehotkey.KeyReturn,
	"return": nativehotkey.KeyReturn,
	"0":      nativehotkey.Key0,
	"1":      nativehotkey.Key1,
	"2":      nativehotkey.Key2,
	"3":      nativehotkey.Key3,
	"4":      nativehotkey.Key4,
	"5":      nativehotkey.Key5,
	"6":      nativehotkey.Key6,
	"7":      nativehotkey.Key7,
	"8":      nativehotkey.Key8,
	"9":      nativehotkey.Key9,
	"a":      nativehotkey.KeyA,
	"b":      nativehotkey.KeyB,
	"c":      nativehotkey.KeyC,
	"d":      nativehotkey.KeyD,
	"e":      nativehotkey.KeyE,
	"f":      nativehotkey.KeyF,
	"g":      nativehotkey.KeyG,
	"h":      nativehotkey.KeyH,
	"i":      nativehotkey.KeyI,
	"j":      nativehotkey.KeyJ,
	"k":      nativehotkey.KeyK,
	"l":      nativehotkey.KeyL,
	"m":      nativehotkey.KeyM,
	"n":      nativehotkey.KeyN,
	"o":      nativehotkey.KeyO,
	"p":      nativehotkey.KeyP,
	"q":      nativehotkey.KeyQ,
	"r":      nativehotkey.KeyR,
	"s":      nativehotkey.KeyS,
	"t":      nativehotkey.KeyT,
	"u":      nativehotkey.KeyU,
	"v":      nativehotkey.KeyV,
	"w":      nativehotkey.KeyW,
	"x":      nativehotkey.KeyX,
	"y":      nativehotkey.KeyY,
	"z":      nativehotkey.KeyZ,
	"f1":     nativehotkey.KeyF1,
	"f2":     nativehotkey.KeyF2,
	"f3":     nativehotkey.KeyF3,
	"f4":     nativehotkey.KeyF4,
	"f5":     nativehotkey.KeyF5,
	"f6":     nativehotkey.KeyF6,
	"f7":     nativehotkey.KeyF7,
	"f8":     nativehotkey.KeyF8,
	"f9":     nativehotkey.KeyF9,
	"f10":    nativehotkey.KeyF10,
	"f11":    nativehotkey.KeyF11,
	"f12":    nativehotkey.KeyF12,
}
