//go:build darwin

package hotkey

import nativehotkey "golang.design/x/hotkey"

var modifiers = map[string]nativehotkey.Modifier{
	"alt":     nativehotkey.Modifier(0x800),
	"option":  nativehotkey.Modifier(0x800),
	"ctrl":    nativehotkey.Modifier(0x1000),
	"control": nativehotkey.Modifier(0x1000),
	"shift":   nativehotkey.Modifier(0x200),
	"cmd":     nativehotkey.Modifier(0x100),
	"command": nativehotkey.Modifier(0x100),
	"meta":    nativehotkey.Modifier(0x100),
	"super":   nativehotkey.Modifier(0x100),
	"win":     nativehotkey.Modifier(0x100),
}

var keys = map[string]nativehotkey.Key{
	"space":  nativehotkey.Key(49),
	"enter":  nativehotkey.Key(0x24),
	"return": nativehotkey.Key(0x24),
	"0":      nativehotkey.Key(29),
	"1":      nativehotkey.Key(18),
	"2":      nativehotkey.Key(19),
	"3":      nativehotkey.Key(20),
	"4":      nativehotkey.Key(21),
	"5":      nativehotkey.Key(23),
	"6":      nativehotkey.Key(22),
	"7":      nativehotkey.Key(26),
	"8":      nativehotkey.Key(28),
	"9":      nativehotkey.Key(25),
	"a":      nativehotkey.Key(0),
	"b":      nativehotkey.Key(11),
	"c":      nativehotkey.Key(8),
	"d":      nativehotkey.Key(2),
	"e":      nativehotkey.Key(14),
	"f":      nativehotkey.Key(3),
	"g":      nativehotkey.Key(5),
	"h":      nativehotkey.Key(4),
	"i":      nativehotkey.Key(34),
	"j":      nativehotkey.Key(38),
	"k":      nativehotkey.Key(40),
	"l":      nativehotkey.Key(37),
	"m":      nativehotkey.Key(46),
	"n":      nativehotkey.Key(45),
	"o":      nativehotkey.Key(31),
	"p":      nativehotkey.Key(35),
	"q":      nativehotkey.Key(12),
	"r":      nativehotkey.Key(15),
	"s":      nativehotkey.Key(1),
	"t":      nativehotkey.Key(17),
	"u":      nativehotkey.Key(32),
	"v":      nativehotkey.Key(9),
	"w":      nativehotkey.Key(13),
	"x":      nativehotkey.Key(7),
	"y":      nativehotkey.Key(16),
	"z":      nativehotkey.Key(6),
	"f1":     nativehotkey.Key(0x7A),
	"f2":     nativehotkey.Key(0x78),
	"f3":     nativehotkey.Key(0x63),
	"f4":     nativehotkey.Key(0x76),
	"f5":     nativehotkey.Key(0x60),
	"f6":     nativehotkey.Key(0x61),
	"f7":     nativehotkey.Key(0x62),
	"f8":     nativehotkey.Key(0x64),
	"f9":     nativehotkey.Key(0x65),
	"f10":    nativehotkey.Key(0x6D),
	"f11":    nativehotkey.Key(0x67),
	"f12":    nativehotkey.Key(0x6F),
}
